name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.9'

      - name: Install dependencies
        run: bun install

      - name: Type check and build
        run: bun run build

      - name: Smoke test (help)
        run: bun start -- --help

      - name: Show config (no env)
        run: bun run dev -- config show

      - name: Show config (from env)
        env:
          BOOKSTACK_URL: https://example.com
          BOOKSTACK_TOKEN_ID: example-id
          BOOKSTACK_TOKEN_SECRET: example-secret
        run: bun run dev -- config show
